# Generated by Django 5.2.5 on 2025-08-27 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='myapp',
            new_name='mydjangodata',
        ),
    ]
