# Generated by Django 5.2.5 on 2025-08-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_myapp_mydjangodata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydjangodata',
            name='img_url',
            field=models.URLField(null=True),
        ),
    ]
