# Generated by Django 5.2.5 on 2025-08-27 17:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_mydjangodata_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydjangodata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
