# Generated by Django 5.2.5 on 2025-08-28 09:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_myappform'),
    ]

    operations = [
        migrations.AddField(
            model_name='myappform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
