# Generated by Django 5.2.5 on 2025-08-29 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_mypost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mypost',
            old_name='Category_id',
            new_name='Category',
        ),
    ]
