# Generated by Django 5.2.5 on 2025-08-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypost',
            name='slug_name',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
